title: YaNing ' s Mar
email: wxhhkr15@foxmail.com
author:
  picture: https://github.com/Yaningnaw/assets/img/compressed/hugo.jpg #URL FORMAT
  name: Hugo Carreira
  location: Rio de Janeiro - Brazil
  description: "19 years old, studying computer science"  
description: Yaninn的博客
baseurl: "/"
url: https://Yaningnaw.github.io
twitter_username: Yaningnaw
github_username:  Yaningnaw
github_url: https://github.com/Yaningnaw

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock